### PR TITLE
Precommit Pipeline: Add GitHub Actions version

### PR DESCRIPTION
**Pull request by sfraint**
Add GitHub Actions version of the precommit pipeline.

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/96)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @arifogel and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/docker/96#-NAAbirw7LGfdciDvmah:-NAAbirw7LGfdciDvmai:b-j6logg) (no related file):*
Example workflow run: https://github.com/batfish/docker/actions/runs/2913237808

___

**Review by arifogel — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/96)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[`.buildkite/wait_for_bf.sh` line 1 at r1](https://reviewable.io/reviews/batfish/docker/96#-NAIIRZaA5WUt1Cg9xXZ:-NAIIRZaA5WUt1Cg9xX_:b1cr5mo) ([raw file](https://github.com/batfish/docker/blob/f10ac4ec218dfbaf430923439d12809fb5d54124/.buildkite/wait_for_bf.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

Why is this in the `.buildkite` directory?
___
*[`tests/test.sh` line 16 at r1](https://reviewable.io/reviews/batfish/docker/96#-NAIKBtJCol3TKNTCDCu:-NAIKBtJCol3TKNTCDCv:bz9uip9) ([raw file](https://github.com/batfish/docker/blob/f10ac4ec218dfbaf430923439d12809fb5d54124/tests/test.sh#L16)):*
> ```Shell
> pushd pybatfish
> # Install test dependencies
> pip3 install "$(ls dist/pybatfish-*-py2.py3-none-any.whl)"[dev]
> ```

nit: in general we should be quoting `[dev]`. Bash first checks if things in `[]` work as a character class for a present file. If not, it leaves it uninterpreted. Not going to be a problem here, but bad practice.
Can just move the close quote from `$()` to after the `]`.

See:
```
arifogel@nova:~/scratch$touch abcd
arifogel@nova:~/scratch$echo abc[dev]
abcd
arifogel@nova:~/scratch$echo ddd[dev]
ddd[dev]
```

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/96)* status: all files reviewed, 2 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[`tests/test.sh` line 16 at r1](https://reviewable.io/reviews/batfish/docker/96#-NAIKBtJCol3TKNTCDCu:-NAILQls-jQCSAlDuJPS:b5jgz1h) ([raw file](https://github.com/batfish/docker/blob/f10ac4ec218dfbaf430923439d12809fb5d54124/tests/test.sh#L16)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nit: in general we should be quoting `[dev]`. Bash first checks if things in `[]` work as a character class for a present file. If not, it leaves it uninterpreted. Not going to be a problem here, but bad practice.
Can just move the close quote from `$()` to after the `]`.

See:
```
arifogel@nova:~/scratch$touch abcd
arifogel@nova:~/scratch$echo abc[dev]
abcd
arifogel@nova:~/scratch$echo ddd[dev]
ddd[dev]
```
</blockquote></details>

With proper quoting for your purpose:
```
arifogel@nova:~/scratch$echo "$(echo abc)[dev]"
abc[dev]
```

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/96)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[`tests/test.sh` line 16 at r1](https://reviewable.io/reviews/batfish/docker/96#-NAIKBtJCol3TKNTCDCu:-NAL1baZ2Y6FXmjWEgth:b-wjb6ye) ([raw file](https://github.com/batfish/docker/blob/f10ac4ec218dfbaf430923439d12809fb5d54124/tests/test.sh#L16)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

With proper quoting for your purpose:
```
arifogel@nova:~/scratch$echo "$(echo abc)[dev]"
abc[dev]
```
</blockquote></details>

good catch, updated
___
*[`.buildkite/wait_for_bf.sh` line 1 at r1](https://reviewable.io/reviews/batfish/docker/96#-NAIIRZaA5WUt1Cg9xXZ:-NAL1T9B9ywngnkXmJs8:b-7mmp82) ([raw file](https://github.com/batfish/docker/blob/f10ac4ec218dfbaf430923439d12809fb5d54124/.buildkite/wait_for_bf.sh#L1)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why is this in the `.buildkite` directory?
</blockquote></details>

moved

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/96)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

**Pull request merged**
