### PR TITLE
CI: add schedule for Precommit workflow

### PR DESCRIPTION
**Pull request by sfraint**

### CODE REVIEW

**Review by dhalperi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/103)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

___
*[`.github/workflows/precommit.yml` line 8 at r1](https://reviewable.io/reviews/batfish/docker/103#-NARDaGo2qeFzJiHkPi0:-NARDaGp-rxXdAQN8tCq:b-rvjeyd) ([raw file](https://github.com/batfish/docker/blob/550f2368f10c61d822cc974a87c307734ce37cf7/.github/workflows/precommit.yml#L8)):*
> ```YAML
>       - master
>   schedule:
>     - cron: '0 * * * *'  # Hourly
> ```

daily?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/103)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

___
*[`.github/workflows/precommit.yml` line 8 at r1](https://reviewable.io/reviews/batfish/docker/103#-NARDaGo2qeFzJiHkPi0:-NARDejT13UClbqiLobu:b-53759l) ([raw file](https://github.com/batfish/docker/blob/550f2368f10c61d822cc974a87c307734ce37cf7/.github/workflows/precommit.yml#L8)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

daily?
</blockquote></details>

or maybe like 2x a day?

Not sure, but we don't really need this every hour right?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/103)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[`.github/workflows/precommit.yml` line 8 at r1](https://reviewable.io/reviews/batfish/docker/103#-NARDaGo2qeFzJiHkPi0:-NARFlrC0_m4l6Ibv-C3:b-wt25md) ([raw file](https://github.com/batfish/docker/blob/550f2368f10c61d822cc974a87c307734ce37cf7/.github/workflows/precommit.yml#L8)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

or maybe like 2x a day?

Not sure, but we don't really need this every hour right?
</blockquote></details>

If 2x per day, I'd recommend at least one of those times is in the middle of the workday.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/103)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[`.github/workflows/precommit.yml` line 8 at r1](https://reviewable.io/reviews/batfish/docker/103#-NARDaGo2qeFzJiHkPi0:-NARFy7v7nTFBWWoMx51:b-llpyh) ([raw file](https://github.com/batfish/docker/blob/550f2368f10c61d822cc974a87c307734ce37cf7/.github/workflows/precommit.yml#L8)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

If 2x per day, I'd recommend at least one of those times is in the middle of the workday.
</blockquote></details>

well, exactly one of those times :P

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/103)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @arifogel and @dhalperi)

___
*[`.github/workflows/precommit.yml` line 8 at r1](https://reviewable.io/reviews/batfish/docker/103#-NARDaGo2qeFzJiHkPi0:-NARGEFQ9G2C7ZBIuSe6:bhtigpd) ([raw file](https://github.com/batfish/docker/blob/550f2368f10c61d822cc974a87c307734ce37cf7/.github/workflows/precommit.yml#L8)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

well, exactly one of those times :P
</blockquote></details>

noon and 5pm?

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/103)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
