### PR TITLE
Add Initial Buildkite Pipelines

### PR DESCRIPTION
**Pull request by sfraint**
Add initial pipelines to automatically build and test docker images.

Both pipelines:
* Build the `batfish` Docker image
* Test the `batfish` image with Pybatfish integration tests _outside_ the container
* Build the `allinone` Docker image
* Test the `allinone` image with Pybatfish integration tests _inside_ the container

`Upload` pipeline will also:
* Upload `test` (and sha) tagged `batfish` and `allinone` image to [Docker Hub](https://hub.docker.com/r/batfish/)
* Block for manual testing ([manual testing instructions here](https://docs.google.com/document/d/15XWSdyHApnVbmZCg3FKpu6ree2HGDysmgYNFhbqTj1Q))
* Promote the `test` tagged Docker Hub images to `latest` images after the block is manually released

For more details, see the [container building design doc](https://docs.google.com/document/d/1VAyMdVQgKLDscVNI8WE1_p-tej40phM5AKD6p4ez7_8/) and [container testing ADR](https://docs.google.com/document/d/1YHtr-b8h1LfXRNohA03s5fDbpsrwJRKKrpNsYTK-flw/).

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/32)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @arifogel, @progwriter, and @sfraint)

___
*[.buildkite/build_batfish.sh, line 13 at r1](https://reviewable.io/reviews/batfish/docker/32#-LeI6i9F9KnHRi9YbYN5:-LeI6i9F9KnHRi9YbYN6:b3766vp) ([raw file](https://github.com/batfish/docker/blob/12d4457ae3532936a902b8c3edfae3e97afc7917/.buildkite/build_batfish.sh#L13)):*
> ```Shell
>   BATFISH_TAG=$(git rev-parse --short HEAD)
> popd
> mvn -f ${BF_DIR}/projects install
> ```

Why use `install`? If this is the terminal `mvn` command in this step, you can just do `package`.
___
*[.buildkite/docker_build_allinone.sh, line 42 at r1](https://reviewable.io/reviews/batfish/docker/32#-LeI9f_KCQKcLC3AhRUa:-LeI9f_KCQKcLC3AhRUb:bc4onw) ([raw file](https://github.com/batfish/docker/blob/12d4457ae3532936a902b8c3edfae3e97afc7917/.buildkite/docker_build_allinone.sh#L42)):*
> ```Shell
> docker tag batfish/allinone:${BF_TAG}_${PYBF_TAG} batfish/allinone:${TESTING_TAG}-${BUILDKITE_BUILD_NUMBER}
> 
> if [ "${2-}" == "" ]; then
> ```

Why 2 here and not 1?
What are the meanings of `$1` and `%2`?
Why is `$2` not referenced elsewhere?

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/32)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @arifogel, @progwriter, and @sfraint)

___
*[.buildkite/docker_build_allinone.sh, line 42 at r1](https://reviewable.io/reviews/batfish/docker/32#-LeI9f_KCQKcLC3AhRUa:-LeIADvlEFzqFs_RoUTP:b-xhsln) ([raw file](https://github.com/batfish/docker/blob/12d4457ae3532936a902b8c3edfae3e97afc7917/.buildkite/docker_build_allinone.sh#L42)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why 2 here and not 1?
What are the meanings of `$1` and `%2`?
Why is `$2` not referenced elsewhere?
</blockquote></details>

Question about unused positional arguments  applies generally

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/32)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @arifogel, @progwriter, and @sfraint)

___
*[.buildkite/docker_build_batfish.sh, line 28 at r1](https://reviewable.io/reviews/batfish/docker/32#-LeIAeliDoeXZW_4h-ge:-LeIAelj0BXfHAuc2IsR:bka1g3z) ([raw file](https://github.com/batfish/docker/blob/12d4457ae3532936a902b8c3edfae3e97afc7917/.buildkite/docker_build_batfish.sh#L28)):*
> ```Shell
> if [ "${1-}" == "" ]; then
>   # Upload the image to Docker Hub if no image file path is specified
>   docker push batfish/batfish:${BF_TAG}
> ```

Can this tag be overwritten in different builds? Should it be?
Should the bulid-specific tag be pushed first?

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/32)* status: 5 of 11 files reviewed, 2 unresolved discussions (waiting on @arifogel, @progwriter, and @sfraint)

**Review by arifogel — COMMENTED** [review]
> Reviewed 6 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/32)* status: all files reviewed, 2 unresolved discussions (waiting on @progwriter and @sfraint)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/32)* status: 6 of 11 files reviewed, 2 unresolved discussions (waiting on @arifogel and @progwriter)

___
*[.buildkite/build_batfish.sh, line 13 at r1](https://reviewable.io/reviews/batfish/docker/32#-LeI6i9F9KnHRi9YbYN5:-LeID19H1JtfrEvTJQiA:bt2vr1b) ([raw file](https://github.com/batfish/docker/blob/12d4457ae3532936a902b8c3edfae3e97afc7917/.buildkite/build_batfish.sh#L13)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why use `install`? If this is the terminal `mvn` command in this step, you can just do `package`.
</blockquote></details>

Fixed.
___
*[.buildkite/docker_build_allinone.sh, line 42 at r1](https://reviewable.io/reviews/batfish/docker/32#-LeI9f_KCQKcLC3AhRUa:-LeICMg6BThrMq9G0bZH:b-77scoi) ([raw file](https://github.com/batfish/docker/blob/12d4457ae3532936a902b8c3edfae3e97afc7917/.buildkite/docker_build_allinone.sh#L42)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Question about unused positional arguments  applies generally
</blockquote></details>

`$2` is used below in the `docker save ...` command.
`$1` is used above, during artifact downloading.

I can add a comment at the top of this script (and others) explicitly laying out the optional arguments to make what's going on a little clearer
___
*[.buildkite/docker_build_batfish.sh, line 28 at r1](https://reviewable.io/reviews/batfish/docker/32#-LeIAeliDoeXZW_4h-ge:-LeID76G7lcczoSdWzwX:b-55504k) ([raw file](https://github.com/batfish/docker/blob/12d4457ae3532936a902b8c3edfae3e97afc7917/.buildkite/docker_build_batfish.sh#L28)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Can this tag be overwritten in different builds? Should it be?
Should the bulid-specific tag be pushed first?
</blockquote></details>

It can be overwritten.  It might be slightly better to defer uploading the sha tagged image until the pipeline is unblocked or just add the build num as part of the tag to ensure it is unique

**Review by arifogel — COMMENTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/32)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi and @progwriter)

___
*[.buildkite/docker_build_batfish.sh, line 28 at r1](https://reviewable.io/reviews/batfish/docker/32#-LeIAeliDoeXZW_4h-ge:-LeI_2kE3213-AHEEENi:bssowfe) ([raw file](https://github.com/batfish/docker/blob/12d4457ae3532936a902b8c3edfae3e97afc7917/.buildkite/docker_build_batfish.sh#L28)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

It can be overwritten.  It might be slightly better to defer uploading the sha tagged image until the pipeline is unblocked or just add the build num as part of the tag to ensure it is unique
</blockquote></details>

@dhalperi do you have insight into proper tagging discipline here? I'm not sure what the consequences might be here.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/32)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @arifogel, @dhalperi, and @progwriter)

___
*[.buildkite/docker_build_batfish.sh, line 28 at r1](https://reviewable.io/reviews/batfish/docker/32#-LeIAeliDoeXZW_4h-ge:-LeJPcMZ2RhKuEEXV6mw:b-1i1o4e) ([raw file](https://github.com/batfish/docker/blob/12d4457ae3532936a902b8c3edfae3e97afc7917/.buildkite/docker_build_batfish.sh#L28)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

@dhalperi do you have insight into proper tagging discipline here? I'm not sure what the consequences might be here.
</blockquote></details>

Chatted with @dhalperi , we can just push sha tagged image during release

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/32)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @progwriter)

**Pull request merged**
