### PR TITLE
Pin pip for tests

### PR DESCRIPTION
**Pull request by sfraint**
Looks like pip 20.3 has issues with dependency resolution, so pin to the last working version.

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/73)* status: 0 of 1 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/batfish/docker/73#-MNZmRtfApJc8MpTXEBH:-MNZmRtfApJc8MpTXEBI:b-qjl1mg) (no related file):*
Upload pipeline run: https://buildkite.com/intentionet/open-source-docker-pipeline/builds/741

---

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/73)* status: all files reviewed, 1 unresolved discussion (waiting on @progwriter and @sfraint)

___
*[tests/test_batfish_container.sh, line 10 at r1](https://reviewable.io/reviews/batfish/docker/73#-MNZx5sY8Wl-FIkN4mUQ:-MNZx5sY8Wl-FIkN4mUR:bx31pri) ([raw file](https://github.com/batfish/docker/blob/860ffd4300b66511c60b5a23c669d99c52d5ee57/tests/test_batfish_container.sh#L10)):*
> ```
> pip 20.3 has problems
> ```
link to https://github.com/pypa/pip/issues/9187 ?

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/73)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @progwriter)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/73)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dhalperi and @progwriter)

___
*[tests/test_batfish_container.sh, line 10 at r1](https://reviewable.io/reviews/batfish/docker/73#-MNZx5sY8Wl-FIkN4mUQ:-MNZxs2u2FXRNixC9kig:bvnrpcm) ([raw file](https://github.com/batfish/docker/blob/860ffd4300b66511c60b5a23c669d99c52d5ee57/tests/test_batfish_container.sh#L10)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> pip 20.3 has problems
> ```
link to https://github.com/pypa/pip/issues/9187 ?
</blockquote></details>

updated

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/73)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @progwriter)

**Pull request merged**
