### PR TITLE
GitHub Actions: integration test workflow

### PR DESCRIPTION
**Pull request by sfraint**
* Add a new reusable workflow for artifact and cross-version integration tests
* Add a new triggered workflow that runs all these tests
* Refactor precommit workflow(s) to run the artifact tests via the new reusable workflow
* Add helper python scripts to query docker and pypi release tags

----

To manually run the python helper scripts:
```
$ python get_docker_versions.py --image batfish/batfish --days=90 --minimum=3 --json-format --pattern=202
["2022.04.06.1263","2022.03.16.1242","2021.12.13.1143"]
```

```
$ python get_pypi_versions.py --package pybatfish --days=90 --minimum=3 --json-format
["2022.3.16.1242","2022.2.18.1216","2021.11.4.1095"]
```

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/102)* status: all files reviewed, 5 unresolved discussions (waiting on @sfraint)

___
*[`get_docker_versions.py` line 24 at r1](https://reviewable.io/reviews/batfish/docker/102#-NAQv3elAj-gwzV33qLh:-NAQv3elAj-gwzV33qLi:b-edroxa) ([raw file](https://github.com/batfish/docker/blob/ff62dfe9de53580fedbb3d59ac4b1242ab1f4420/get_docker_versions.py#L24)):*
> ```Python
>     res = list()
>     for v in versions:
>         recent = dates.get(v) > datetime.now() - timedelta(days=days)
> ```

nit: should only call `datetime.now()` once above the loop
___
*[`get_docker_versions.py` line 30 at r1](https://reviewable.io/reviews/batfish/docker/102#-NAQvUM1DhlIxDbd_E7z:-NAQvUM1DhlIxDbd_E8-:b-yqo6w4) ([raw file](https://github.com/batfish/docker/blob/ff62dfe9de53580fedbb3d59ac4b1242ab1f4420/get_docker_versions.py#L30)):*
> ```Python
> 
> if __name__ == "__main__":
>     parser = argparse.ArgumentParser(description='Get PyPI versions for a date-versioned package, e.g. Pybatfish.')
> ```

(Optional)
If we ever want to test this stuff, this block should just call a function, and then should pass explicit args to `parse_args` assuming that's a thing.
Similarly, the result of `requests.get` above should be an arg passed to `get_relevant_releases`, and perhaps also the current time.
___
*[`get_pypi_versions.py` line 9 at r1](https://reviewable.io/reviews/batfish/docker/102#-NAQwWbhBcBcjwt1lkOv:-NAQwWbhBcBcjwt1lkOw:b-wug07j) ([raw file](https://github.com/batfish/docker/blob/ff62dfe9de53580fedbb3d59ac4b1242ab1f4420/get_pypi_versions.py#L9)):*
> ```Python
> import requests
> 
> def get_relevant_releases(package: str, days: int, minimum: int) -> List[str]:
> ```

Why not factor this out? Is there any difference from the version in `get_docker_versions` other than the base URL?
___
*[`.github/workflows/reusable-integration-tests.yml` line 44 at r1](https://reviewable.io/reviews/batfish/docker/102#-NAQxJXl5M6ffikQmWpJ:-NAQxJXl5M6ffikQmWpK:bnv6n2h) ([raw file](https://github.com/batfish/docker/blob/ff62dfe9de53580fedbb3d59ac4b1242ab1f4420/.github/workflows/reusable-integration-tests.yml#L44)):*
> ```YAML
>       - id: set_versions
>         run: |
>           DATE_TAGS="$(python get_docker_versions.py --image batfish/batfish --days=${{ inputs.bf_test_artifact_age }} --minimum=${{ inputs.bf_min_release_test_count }} --json-format --pattern=202)"
> ```

Can you add a comment about this pattern?
___
*[`.github/workflows/reusable-integration-tests.yml` line 62 at r1](https://reviewable.io/reviews/batfish/docker/102#-NAQxZgB3U2tnpgydIo6:-NAQxZgB3U2tnpgydIo7:bsmzbp9) ([raw file](https://github.com/batfish/docker/blob/ff62dfe9de53580fedbb3d59ac4b1242ab1f4420/.github/workflows/reusable-integration-tests.yml#L62)):*
> ```YAML
>       - id: set_versions
>         run: |
>           PYBF_TAGS="$(python get_pypi_versions.py --package pybatfish --days=${{ inputs.bf_test_artifact_age }} --minimum=${{ inputs.pybf_min_release_test_count }} --json-format)"
> ```

(Applies in multiple places)
If `get_pypi_versions.py` fails, does the step fail or silently succeed without testing anything?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/102)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @arifogel)

___
*[`get_docker_versions.py` line 24 at r1](https://reviewable.io/reviews/batfish/docker/102#-NAQv3elAj-gwzV33qLh:-NAR12d45cGrVD6ZA6yN:bvnrpcm) ([raw file](https://github.com/batfish/docker/blob/ff62dfe9de53580fedbb3d59ac4b1242ab1f4420/get_docker_versions.py#L24)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nit: should only call `datetime.now()` once above the loop
</blockquote></details>

updated
___
*[`get_docker_versions.py` line 30 at r1](https://reviewable.io/reviews/batfish/docker/102#-NAQvUM1DhlIxDbd_E7z:-NAR14PmA1k4FbHYaB98:bklbt4x) ([raw file](https://github.com/batfish/docker/blob/ff62dfe9de53580fedbb3d59ac4b1242ab1f4420/get_docker_versions.py#L30)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

(Optional)
If we ever want to test this stuff, this block should just call a function, and then should pass explicit args to `parse_args` assuming that's a thing.
Similarly, the result of `requests.get` above should be an arg passed to `get_relevant_releases`, and perhaps also the current time.
</blockquote></details>

I did a little refactoring.

re: `get_relevant_releases`, we can refactor this later if needed. But I'd probably just refactor it into two parts: 1) get a dict of release tag to datetime and 2) build list of applicable release tags from the dict
___
*[`get_pypi_versions.py` line 9 at r1](https://reviewable.io/reviews/batfish/docker/102#-NAQwWbhBcBcjwt1lkOv:-NAQyg4q3jcmsUYagbjy:bf715my) ([raw file](https://github.com/batfish/docker/blob/ff62dfe9de53580fedbb3d59ac4b1242ab1f4420/get_pypi_versions.py#L9)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why not factor this out? Is there any difference from the version in `get_docker_versions` other than the base URL?
</blockquote></details>

There are a few differences: you have to extract different things in different formats from the JSON responses, timestamps are different formats, then we also need to do some regex matching in the docker hub one (since we have prod and dev images in the same place).

Also, it's nice that each script is trivially self-contained.
___
*[`.github/workflows/reusable-integration-tests.yml` line 44 at r1](https://reviewable.io/reviews/batfish/docker/102#-NAQxJXl5M6ffikQmWpJ:-NAQzo4QD61jjs01AQGL:b-7tfmjp) ([raw file](https://github.com/batfish/docker/blob/ff62dfe9de53580fedbb3d59ac4b1242ab1f4420/.github/workflows/reusable-integration-tests.yml#L44)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Can you add a comment about this pattern?
</blockquote></details>

added
___
*[`.github/workflows/reusable-integration-tests.yml` line 62 at r1](https://reviewable.io/reviews/batfish/docker/102#-NAQxZgB3U2tnpgydIo6:-NAR-7aS1M25bxH_zK6A:b-ej64uz) ([raw file](https://github.com/batfish/docker/blob/ff62dfe9de53580fedbb3d59ac4b1242ab1f4420/.github/workflows/reusable-integration-tests.yml#L62)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

(Applies in multiple places)
If `get_pypi_versions.py` fails, does the step fail or silently succeed without testing anything?
</blockquote></details>

Nope, the step fails too, e.g. see https://github.com/batfish/docker/runs/8027592213?check_suite_focus=true where I used the wrong script/left off a required param

**Review by arifogel — COMMENTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/102)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel)

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/102)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
