### PR TITLE
Add Batfish and allinone image dockerfiles, scripts

### PR DESCRIPTION
**Pull request by sfraint**
Add dockerfiles + script to generate and push docker images for:

1) Batfish
2) "allinone" (Batfish + Pybatfish + Jupyter) - Batfish and Jupyter are both run in parallel via a wrapper script inside the docker container

The build script can build these images for specific commits or from master/head (default), runs integration tests between Pybatfish and the built Batfish container, and pushes the docker images to docker hub if the builds and tests are successful.

### CODE REVIEW

**Comment by sfraint** [comment]
Readme still needs a bit of review and work.

Also will need to update Batfish and Pybatfish readme's/getting started guides to point to the public docker images.

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/1)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @progwriter, @haverma, and @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/docker/1#-LMdz5Wa0pY3ApBl-6_i:-LMdz5Wa0pY3ApBl-6_j:b6u596p) (no related file):*
Taking over for a bit, working on some improvements.

---

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/1)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @sfraint, @haverma, and @corinaminer)

*[a discussion](https://reviewable.io/reviews/batfish/docker/1#-LMiaZS3CutyGuAeWo01:-LMiaZS482tl7n19X-BY:b-dg18si) (no related file):*
@corinaminer Can you do me a favor and test the instructions in `allinone.md` as a sanity check?

---

**Review by corinaminer — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/1)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @sfraint and @dhalperi)

___
*[allinone.md, line 11 at r4](https://reviewable.io/reviews/batfish/docker/1#-LMip8xK93d_USumIalu:-LMip8xK93d_USumIalv:bittjls) ([raw file](https://github.com/batfish/docker/blob/2b1764b383464eccf80e437647e39c4481cf7120/allinone.md#L11)):*
> ```Markdown
> ## Running the image, no persistent storage
> 
> To run the `allinone` docker image for the first time, run:
> ```

Is it even worth showing how to run the image without persistent storage?

Pros of showing only persistent storage:
- Simplifies readme; users don't have to choose one of two ways to run
- Easy for users to dig into file system if they want (most probably won't)
- Data is persistent; snapshots and questions won't be lost. But Pybatfish users wouldn't normally reuse much persistent data anyway (for now)

Cons:
- default setup is slightly more complicated
- people might not want arbitrary batfish data stored locally?

**Comment by progwriter** [comment]
___
*[allinone.md, line 11 at r4](https://reviewable.io/reviews/batfish/docker/1#-LMip8xK93d_USumIalu:-LMizP7E12Bou-RWjCHT:by3b95r) ([raw file](https://github.com/batfish/docker/blob/2b1764b383464eccf80e437647e39c4481cf7120/allinone.md#L11)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

Is it even worth showing how to run the image without persistent storage?

Pros of showing only persistent storage:
- Simplifies readme; users don't have to choose one of two ways to run
- Easy for users to dig into file system if they want (most probably won't)
- Data is persistent; snapshots and questions won't be lost. But Pybatfish users wouldn't normally reuse much persistent data anyway (for now)

Cons:
- default setup is slightly more complicated
- people might not want arbitrary batfish data stored locally?
</blockquote></details>

I claim yes. Most people will not want pollution of their hard drive on the first go.

This readme pattern is common for database docker images (as an example). Play around first, if you need persistence, extra steps needed.

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 8 files at r2, 2 of 3 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/1#-:-LMj8XAZ7QgRsxmFwDwT:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @corinaminer, @sfraint, and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/docker/1#-LMiaZS3CutyGuAeWo01:-LMj8_tNB_VsviKhKtsN:b-545ji9) (no related file):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

@corinaminer Can you do me a favor and test the instructions in `allinone.md` as a sanity check?
</blockquote></details>

done, also checked that the batfish-only image works with my local pybatfish.

---
___
*[build_images.sh, line 94 at r4](https://reviewable.io/reviews/batfish/docker/1#-LMj19Jb8wYrkUJhzNpo:-LMj19Jb8wYrkUJhzNpp:b-nc9dzm) ([raw file](https://github.com/batfish/docker/blob/2b1764b383464eccf80e437647e39c4481cf7120/build_images.sh#L94)):*
> ```Shell
> virtualenv .env
> source .env/bin/activate
> pip install jupyter jupyter_client nbconvert pytest wheel
> ```

i think jupyter and nbconvert shouldn't be needed here since they're included in pybatfish's requirements

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dhalperi)

___
*[build_images.sh, line 94 at r4](https://reviewable.io/reviews/batfish/docker/1#-LMj19Jb8wYrkUJhzNpo:-LMjSXH55RrEtRFdw-Oz:b9g4i96) ([raw file](https://github.com/batfish/docker/blob/2b1764b383464eccf80e437647e39c4481cf7120/build_images.sh#L94)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

i think jupyter and nbconvert shouldn't be needed here since they're included in pybatfish's requirements
</blockquote></details>

True, but only as dev extras... we need to clean this section up a little later. Will file issue.

**Pull request merged**
