### PR TITLE
Integration Tests: Limit RAM

### PR DESCRIPTION
**Pull request by sfraint**
Limit RAM for containers run during integration testing.

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/98)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @arifogel and @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/docker/98#-NAC1ipy89HYIovfV6Or:-NAC1ipzCWAY_Tq_rnb3:b-k58nb5) (no related file):*
Two runs in a row passed: https://buildkite.com/batfish/docker-pre-commit/builds/1524 and the PR run https://buildkite.com/batfish/docker-pre-commit/builds/1527

___

**Comment by dhalperi** [comment]
Have you uncovered the reason for the behavior change? I do not want to
work around this until then.

**Review by sfraint — COMMENTED** [review]
No, I'm still not sure; @arifogel any ideas?

> *[Reviewable](https://reviewable.io/reviews/batfish/docker/98#-:-NAC4H-S6gy2p984hPEp:b-7gfqa4)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @arifogel and @dhalperi)

**Review by dhalperi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/98)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @arifogel)

**Pull request merged**
