### PR TITLE
Upgrade pip

### PR DESCRIPTION
**Pull request by sfraint**
Upgrade `pip` in `allinone` image.

Ubuntu installs `pip` `8.1.1` by default (which is lacking a few helpful features like [python_requires specification](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires)).

### CODE REVIEW

**Review by progwriter — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/38)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[allinone.dockerfile, line 19 at r1](https://reviewable.io/reviews/batfish/docker/38#-LfQvvMd8tqxS1Kj2Ar2:-LfQvvMeDLnPKo68w80V:bs8diks) ([raw file](https://github.com/batfish/docker/blob/7fd2da529369f92b7fc18dc8895528816c7152e8/allinone.dockerfile#L19)):*
> ```Dockerfile
>     && rm -rf /var/lib/apt/lists/*
> 
> RUN pip3 install --upgrade pip
> ```

any reason for this to be a separate layer?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/38)* status: all files reviewed, 1 unresolved discussion (waiting on @progwriter)

___
*[allinone.dockerfile, line 19 at r1](https://reviewable.io/reviews/batfish/docker/38#-LfQvvMd8tqxS1Kj2Ar2:-LfQw45Y4bRfJaDRn7El:b-fsl5xf) ([raw file](https://github.com/batfish/docker/blob/7fd2da529369f92b7fc18dc8895528816c7152e8/allinone.dockerfile#L19)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

any reason for this to be a separate layer?
</blockquote></details>

was just separating `pip` action from `apt` actions, I can merge them if you have a strong preference

**Review by progwriter — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/38)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[allinone.dockerfile, line 19 at r1](https://reviewable.io/reviews/batfish/docker/38#-LfQvvMd8tqxS1Kj2Ar2:-LfQwVPBD2fEBLhDf_gl:b-8qm0ez) ([raw file](https://github.com/batfish/docker/blob/7fd2da529369f92b7fc18dc8895528816c7152e8/allinone.dockerfile#L19)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

was just separating `pip` action from `apt` actions, I can merge them if you have a strong preference
</blockquote></details>

worth merging, otherwise it might result in a larger image.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/38)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @progwriter)

___
*[allinone.dockerfile, line 19 at r1](https://reviewable.io/reviews/batfish/docker/38#-LfQvvMd8tqxS1Kj2Ar2:-LfQxWBM20321HVN4MX0:b-896fix) ([raw file](https://github.com/batfish/docker/blob/7fd2da529369f92b7fc18dc8895528816c7152e8/allinone.dockerfile#L19)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

worth merging, otherwise it might result in a larger image.
</blockquote></details>

Done.

**Review by progwriter — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/38#-:-LfQxibP3YtODejSGZZL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
