### PR TITLE
Update container usage instructions in readmes

### PR DESCRIPTION
**Pull request by sfraint**
* Remove distracting info
* Clarify options for running containers

### CODE REVIEW

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/11)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @sfraint, @corinaminer, @saparikh, and @ratulm)

___
*[allinone.md, line 48 at r1](https://reviewable.io/reviews/batfish/docker/11#-LNtv3fc-i82OYuaxPOa:-LNtv3fc-i82OYuaxPOb:b-kv4br9) ([raw file](https://github.com/batfish/docker/blob/7b4f8ac53278baa10bfc3b112786d5d0b3013303/allinone.md#L48)):*
> ```Markdown
>       -v $(pwd)/networks:/notebooks/custom_networks:ro \
>       -v $(pwd)/data:/data -v /etc/group:/etc/group:ro \
>       -v /etc/passwd:/etc/passwd:ro --user=$(id -u):$(id -g) \
> ```

What happens on machines without /etc/{group,passwd}?

Why is this stuff not needed for Batfish docker image?

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/11)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @sfraint, @corinaminer, @saparikh, and @ratulm)

___
*[allinone.md, line 17 at r1](https://reviewable.io/reviews/batfish/docker/11#-LNtytjqBzsY72_q1sRo:-LNtytjqBzsY72_q1sRp:by96lc0) ([raw file](https://github.com/batfish/docker/blob/7b4f8ac53278baa10bfc3b112786d5d0b3013303/allinone.md#L17)):*
> ```Markdown
> To run the `allinone` docker image for the first time, using only the notebooks and example network bundled with the image:
> 
> 1. Run `docker run -p 8888:8888 batfish/allinone`.  Note that after the container starts, Jupyter will show a token required to access notebooks (e.g. token=`abcdef123456...`).
> ```

Why is docker pull not needed here, when its needed for the two cases below?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/11)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @sfraint, @corinaminer, @saparikh, and @ratulm)

___
*[allinone.md, line 17 at r1](https://reviewable.io/reviews/batfish/docker/11#-LNtytjqBzsY72_q1sRo:-LNubX793qT8adfeV2jt:brzhxlc) ([raw file](https://github.com/batfish/docker/blob/7b4f8ac53278baa10bfc3b112786d5d0b3013303/allinone.md#L17)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Why is docker pull not needed here, when its needed for the two cases below?
</blockquote></details>

It is not strictly needed in any case (if no matching image is present, then the pull is done automatically), it just makes sure you are using the latest version of the image.

To avoid confusion, we could just remove that entirely and optionally add it in another section at the end - `Upgrading images`
___
*[allinone.md, line 48 at r1](https://reviewable.io/reviews/batfish/docker/11#-LNtv3fc-i82OYuaxPOa:-LNucVPBBrCNKW_86fom:b-13ltju) ([raw file](https://github.com/batfish/docker/blob/7b4f8ac53278baa10bfc3b112786d5d0b3013303/allinone.md#L48)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

What happens on machines without /etc/{group,passwd}?

Why is this stuff not needed for Batfish docker image?
</blockquote></details>

I haven't tried it, but I think on Windows you wouldn't need those volume or the `--user=` flags.  Do you think we should provide an alternative command for users running Docker in Windows?

We probably should be doing the same thing for the Batfish image that mounts the read-write directory - the ways it's setup now, non-root users may have trouble accessing the Batfish data directory.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/11)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @sfraint, @ratulm, @corinaminer, and @saparikh)

___
*[allinone.md, line 48 at r1](https://reviewable.io/reviews/batfish/docker/11#-LNtv3fc-i82OYuaxPOa:-LNuf4lIDNoN_XoEuFP5:b48w9dp) ([raw file](https://github.com/batfish/docker/blob/7b4f8ac53278baa10bfc3b112786d5d0b3013303/allinone.md#L48)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

I haven't tried it, but I think on Windows you wouldn't need those volume or the `--user=` flags.  Do you think we should provide an alternative command for users running Docker in Windows?

We probably should be doing the same thing for the Batfish image that mounts the read-write directory - the ways it's setup now, non-root users may have trouble accessing the Batfish data directory.
</blockquote></details>

Though, if we don't want the user to view the data Batfish has saved on disk (and just allow Batfish to access it across different containers), then the current Batfish instructions should be fine.

**Review by corinaminer — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/11)* status: all files reviewed, 4 unresolved discussions (waiting on @ratulm, @sfraint, and @saparikh)

___
*[batfish.md, line 3 at r2](https://reviewable.io/reviews/batfish/docker/11#-LO-VTUD0wSpGAKjxaO-:-LO-VTUD0wSpGAKjxaO0:beqopei) ([raw file](https://github.com/batfish/docker/blob/49f464c63b15730d7b42d9eee710436800534efa/batfish.md#L3)):*
> ```Markdown
> # Batfish service docker image
> 
> This image contains only the core Batfish service.
> ```

This could have another sentence linking to the allinone image. ("For a simpler option to get started, try our allinone image that also includes...")
___
*[batfish.md, line 35 at r2](https://reviewable.io/reviews/batfish/docker/11#-LO-WZ4jDQGR0ctxvD-U:-LO-WZ4jDQGR0ctxvD-V:b-6nglos) ([raw file](https://github.com/batfish/docker/blob/49f464c63b15730d7b42d9eee710436800534efa/batfish.md#L35)):*
> ```Markdown
>     Then you can restart the container with same docker run command you used to start it (e.g. `docker run -p 9997:9997 -p 9996:9996 batfish/batfish`).
> 
>     Note if running with persistent storage, previously uploaded network snapshots may be incompatible with newer version of Batfish and may need to be re-uploaded.
> ```

"newer version**s**"? (also applies to the other readme)

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/11)* status: all files reviewed, 3 unresolved discussions (waiting on @sfraint and @saparikh)

___
*[batfish.md, line 19 at r2](https://reviewable.io/reviews/batfish/docker/11#-LO1DQxW1znK-tSEpJ5i:-LO1DQxW1znK-tSEpJ5j:bf98xw4) ([raw file](https://github.com/batfish/docker/blob/49f464c63b15730d7b42d9eee710436800534efa/batfish.md#L19)):*
> ```Markdown
> You can now use the [Pybatfish client](pybf) on the host machine to interact with the service.
> 
> ### Running with persistent storage
> ```

As we discussed, lets only provide this option.

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/11)* status: all files reviewed, 3 unresolved discussions (waiting on @sfraint and @saparikh)

___
*[batfish.md, line 3 at r2](https://reviewable.io/reviews/batfish/docker/11#-LO-VTUD0wSpGAKjxaO-:-LO1Defp2nlfIxxjn79j:b-azzems) ([raw file](https://github.com/batfish/docker/blob/49f464c63b15730d7b42d9eee710436800534efa/batfish.md#L3)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

This could have another sentence linking to the allinone image. ("For a simpler option to get started, try our allinone image that also includes...")
</blockquote></details>

I'd argue against it. Lets just curate one experience. Additional pointers are just distractions when one is trying to get started.

**Review by corinaminer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/11)* status: all files reviewed, 2 unresolved discussions (waiting on @sfraint and @saparikh)

___
*[batfish.md, line 3 at r2](https://reviewable.io/reviews/batfish/docker/11#-LO-VTUD0wSpGAKjxaO-:-LO4BWNUCKwNy6G3fzNv:bb6mt9b) ([raw file](https://github.com/batfish/docker/blob/49f464c63b15730d7b42d9eee710436800534efa/batfish.md#L3)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

I'd argue against it. Lets just curate one experience. Additional pointers are just distractions when one is trying to get started. 
</blockquote></details>

:+1:

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/11)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @corinaminer, @sfraint, and @saparikh)

___
*[batfish.md, line 35 at r2](https://reviewable.io/reviews/batfish/docker/11#-LO-WZ4jDQGR0ctxvD-U:-LO0aJF4BRgymnODJBeR:b-896fix) ([raw file](https://github.com/batfish/docker/blob/49f464c63b15730d7b42d9eee710436800534efa/batfish.md#L35)):*
<details><summary><i>Previously, corinaminer (Corina Miner) wrote…</i></summary><blockquote>

"newer version**s**"? (also applies to the other readme)
</blockquote></details>

Done.

**Review by corinaminer — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/11#-:-LO5QsUgDvOgkmk8NgYV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @saparikh)

**Pull request merged**
