### PR TITLE
More container tests vs dev Pybatfish

### PR DESCRIPTION
**Pull request by sfraint**
Run Pybatfish integration tests against recent Batfish containers

Default behavior is to:
* Test `dev` Pybf versus `latest` and `dev` (built earlier in the same pipeline run) `batfish/batfish` containers
* Test `dev` Pybf versus `batfish/batfish` containers with a tag that starts with a date in the past 31 days (tags like `YYYY.M.D.#` and `YYYY.MM.DD` would both work)

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/49)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @progwriter and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/docker/49#-LsK07T_AWbmfjAcvBLL:-LsK07T_AWbmfjAcvBLM:b-5kifif) (no related file):*
Still need to set `bf_version` env var based on which container we're testing

---

**Review by progwriter — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/49)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

**Review by progwriter — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/49)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

**Review by progwriter — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/49)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
