### PR TITLE
.buildkite/pipeline.sh: make the pipeline a dag

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Comment by dhalperi** [comment]
https://buildkite.com/intentionet/open-source-docker-pipeline/builds/723/dag
https://buildkite.com/batfish/docker-pre-commit/builds/704/dag

**Comment by dhalperi** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/docker/71#-MMb6iR58BatJLzIXxns:-MMb6iR58BatJLzIXxnt:bqxizur) (no related file):*
I can't yet figure out why the pybatfish dev are trying to get questions from the batfish dev build. Shouldn't they be only from the container?

---

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/71)* status: all files reviewed, 1 unresolved discussion

**Review by sfraint — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/71)* status: all files reviewed, 1 unresolved discussion

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/71)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
