### PR TITLE
CI: add artifact upload/release to workflow

### PR DESCRIPTION
**Pull request by sfraint**
This update adds test artifact uploading and optionally production artifact uploading to the "Cross-version and Upload" workflow.

----

* Use `test-` prefixed docker image tags
  * to match existing tag names in the buildkite upload pipeline
* Use the generated bf_version (YYYY.MM.DD.####) as the test- tag suffix
  * to prevent collisions with buildkite upload pipeline's old artifacts
* Add reusable upload workflow
  * Uploads test docker images
  * Uploads pybf to Test PyPI
  * Optionally uploads prod docker images
  * Optionally uploads pybf to PyPI and creates a release branch in pybf repo

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/106)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @arifogel, @dhalperi, and @sfraint)

___
*[`.github/workflows/cross_version_test.yml` line 59 at r2](https://reviewable.io/reviews/batfish/docker/106#-NAzPnuu9X6qiR21Uqyw:-NAzPnuvEn0r-1wk1wPj:b-5wv9gg) ([raw file](https://github.com/batfish/docker/blob/2ce4abdc924b7d18f13f568b57f7785f0c03b809/.github/workflows/cross_version_test.yml#L59)):*
> ```YAML
>       queue_prod_release: ${{ github.event.schedule == '0 15 * * *' }}
>       test_tag: "test-${{ needs.precommit.outputs.bf_version }}"
>       # TODO remote the manual-test- prefix
> ```

I sprinkled some `TODO`s around, for the changes I will need to make before merging this workflow - to actually publish release artifacts.



_Code quote:_
```YAML
      # TODO remote the manual-test- prefix
```

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/106)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @arifogel, @dhalperi, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/docker/106#-NAzQJZP1Tntd2oV8taF:-NAzQJZP1Tntd2oV8taG:btvj7h) (no related file):*
Here is an example workflow run: https://github.com/batfish/docker/actions/runs/2980599961

Note: intentionally left out production artifact upload

___

**Review by arifogel — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/106)* status: all files reviewed, 8 unresolved discussions (waiting on @dhalperi and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/docker/106#-NAzcKQC1zjkTrzVpTHf:-NAzcKQC1zjkTrzVpTHg:b-vi7mob) (no related file):*
Sanity check: who will have permission to trigger upload after this PR?

___
___
*[`.github/workflows/cross_version_test.yml` line 56 at r2](https://reviewable.io/reviews/batfish/docker/106#-NAzZCL94dnVtDSix6yL:-NAzZCL94dnVtDSix6yM:b-o37soj) ([raw file](https://github.com/batfish/docker/blob/2ce4abdc924b7d18f13f568b57f7785f0c03b809/.github/workflows/cross_version_test.yml#L56)):*
> ```YAML
>     with:
>       bf_version: ${{ needs.precommit.outputs.bf_version }}
>       # Consider each 8AM scheduled build as a release candidate
> ```

nit: add `Pacific` to the comment
___
*[`.github/workflows/cross_version_test.yml` line 57 at r2](https://reviewable.io/reviews/batfish/docker/106#-NAzZ0Tn48g5MI8YTOxW:-NAzZ0Tn48g5MI8YTOxX:bxf09fi) ([raw file](https://github.com/batfish/docker/blob/2ce4abdc924b7d18f13f568b57f7785f0c03b809/.github/workflows/cross_version_test.yml#L57)):*
> ```YAML
>       bf_version: ${{ needs.precommit.outputs.bf_version }}
>       # Consider each 8AM scheduled build as a release candidate
>       queue_prod_release: ${{ github.event.schedule == '0 15 * * *' }}
> ```

This is pretty hacky. No way to add anything else to that cron item you can evaluate here?
___
*[`.github/workflows/reusable-upload.yml` line 14 at r2](https://reviewable.io/reviews/batfish/docker/106#-NAz_a3d6FwZv3wTQ7-u:-NAz_a3d6FwZv3wTQ7-v:b-w13ieg) ([raw file](https://github.com/batfish/docker/blob/2ce4abdc924b7d18f13f568b57f7785f0c03b809/.github/workflows/reusable-upload.yml#L14)):*
> ```YAML
>         type: boolean
>       test_tag:
>         description: "Tag for test/dev containers (note: Pybatfish release 'tags' must be numeric and use `bf_version` instead)"
> ```

Don't pybatfish release tags have to not include leading zeros in components? You're not breaking that anywhere in this PR are you?
___
*[`.github/workflows/reusable-upload.yml` line 31 at r2](https://reviewable.io/reviews/batfish/docker/106#-NAzborn6OXCsU-E6JBb:-NAzborn6OXCsU-E6JBc:b-oxgnxg) ([raw file](https://github.com/batfish/docker/blob/2ce4abdc924b7d18f13f568b57f7785f0c03b809/.github/workflows/reusable-upload.yml#L31)):*
> ```YAML
>         default: 'batfish/pybatfish'
>         type: string
>       BATFISH_GITHUB_PYBATFISH_REF:
> ```

No `BATFISH_GITHUB_BATFISH_REF`?
___
*[`.github/workflows/reusable-upload.yml` line 84 at r2](https://reviewable.io/reviews/batfish/docker/106#-NAzcCPNB0La-XuIepcr:-NAzcCPNB0La-XuIepcs:b-8c91yj) ([raw file](https://github.com/batfish/docker/blob/2ce4abdc924b7d18f13f568b57f7785f0c03b809/.github/workflows/reusable-upload.yml#L84)):*
> ```YAML
>           docker push batfish/allinone:${{ inputs.test_tag }}
>   dev_whl_upload:
>     if: inputs.BATFISH_GITHUB_BATFISH_REPO == 'batfish/batfish' && inputs.BATFISH_GITHUB_PYBATFISH_REPO == 'batfish/pybatfish'
> ```

Why does this matter? Why shouldn't you be able to push something from a fork? But if you are making this restriction, shouldn't you restrict to master ref as well?
___
*[`.github/workflows/reusable-upload.yml` line 187 at r2](https://reviewable.io/reviews/batfish/docker/106#-NAzd6LpCcZhOSPMwIJ-:-NAzd6LpCcZhOSPMwIJ0:b-946f6s) ([raw file](https://github.com/batfish/docker/blob/2ce4abdc924b7d18f13f568b57f7785f0c03b809/.github/workflows/reusable-upload.yml#L187)):*
> ```YAML
>         run: |
>           cd pybatfish
>           sed -i.bak -e "s/^__version__ = .*$/__version__ = \"${{ inputs.bf_version }}\"/" pybatfish/__init__.py
> ```

Related to earlier comment. Is this resulting version string used in all the appropriate places?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/106)* status: 4 of 5 files reviewed, 8 unresolved discussions (waiting on @arifogel, @dhalperi, and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/docker/106#-NAzcKQC1zjkTrzVpTHf:-NAzftoYDDLROrZ26ykr:b-eclofz) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Sanity check: who will have permission to trigger upload after this PR?
</blockquote></details>

Good question, I forgot to add a note about that.

1. Batfish release occurs in the `Release Containers` [environment](https://github.com/batfish/docker/settings/environments/614720742/edit), which currently requires manual approval from someone in the `batfish-devs` group (we can change that to `batfish-admins` or any other group we want)
2. Pybf release occurs in the `Release Pybatfish` [environment](https://github.com/batfish/docker/settings/environments/614723686/edit), currently has the same restrictions as number 1 above, but we can independently adjust the two environments

___
___
*[`.github/workflows/cross_version_test.yml` line 56 at r2](https://reviewable.io/reviews/batfish/docker/106#-NAzZCL94dnVtDSix6yL:-NAzh9oj0RC82oJ9O8Bg:b-7tfmjp) ([raw file](https://github.com/batfish/docker/blob/2ce4abdc924b7d18f13f568b57f7785f0c03b809/.github/workflows/cross_version_test.yml#L56)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

nit: add `Pacific` to the comment
</blockquote></details>

added
___
*[`.github/workflows/cross_version_test.yml` line 57 at r2](https://reviewable.io/reviews/batfish/docker/106#-NAzZ0Tn48g5MI8YTOxW:-NAzgsm17P5iKsvGPLwn:bw81p6d) ([raw file](https://github.com/batfish/docker/blob/2ce4abdc924b7d18f13f568b57f7785f0c03b809/.github/workflows/cross_version_test.yml#L57)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

This is pretty hacky. No way to add anything else to that cron item you can evaluate here?
</blockquote></details>

This is pretty close to what [GitHub documentation examples](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) use:
```
on:
  schedule:
    - cron: '30 5 * * 1,3'
    - cron: '30 5 * * 2,4'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"
```

But afaik you can't attach more metadata to the cron trigger
___
*[`.github/workflows/reusable-upload.yml` line 14 at r2](https://reviewable.io/reviews/batfish/docker/106#-NAz_a3d6FwZv3wTQ7-u:-NAzheVZA3YuH4tIpzKx:bnea49s) ([raw file](https://github.com/batfish/docker/blob/2ce4abdc924b7d18f13f568b57f7785f0c03b809/.github/workflows/reusable-upload.yml#L14)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Don't pybatfish release tags have to not include leading zeros in components? You're not breaking that anywhere in this PR are you?
</blockquote></details>

PyPI canonicalizes the published or requested version numbers, e.g. see the Test PyPI upload from this workflow: https://test.pypi.org/project/pybatfish/2022.9.2.60/ which worked just fine
___
*[`.github/workflows/reusable-upload.yml` line 31 at r2](https://reviewable.io/reviews/batfish/docker/106#-NAzborn6OXCsU-E6JBb:-NAzhtKJ57zGKcz__5Dp:bgku5iz) ([raw file](https://github.com/batfish/docker/blob/2ce4abdc924b7d18f13f568b57f7785f0c03b809/.github/workflows/reusable-upload.yml#L31)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

No `BATFISH_GITHUB_BATFISH_REF`?
</blockquote></details>

Not needed (at least yet) - we're checking the repos to make sure they're in the batfish org, then we need the pybf ref to create a release branch from.

We don't do anything with the Batfish ref yet.
___
*[`.github/workflows/reusable-upload.yml` line 84 at r2](https://reviewable.io/reviews/batfish/docker/106#-NAzcCPNB0La-XuIepcr:-NAzi8cy14NCwa_NS64-:b-l2o7cy) ([raw file](https://github.com/batfish/docker/blob/2ce4abdc924b7d18f13f568b57f7785f0c03b809/.github/workflows/reusable-upload.yml#L84)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Why does this matter? Why shouldn't you be able to push something from a fork? But if you are making this restriction, shouldn't you restrict to master ref as well?
</blockquote></details>

This workflow is specifically related to uploading test and release artifacts. We should never allow creating official, public artifacts from fork.

I expect we might want to restrict ref to some extent, but we should also allow releasing from a `release-###.patch#` branch or something like that
___
*[`.github/workflows/reusable-upload.yml` line 187 at r2](https://reviewable.io/reviews/batfish/docker/106#-NAzd6LpCcZhOSPMwIJ-:-NAziWnR0Bbv661Bk6ia:bulf5ez) ([raw file](https://github.com/batfish/docker/blob/2ce4abdc924b7d18f13f568b57f7785f0c03b809/.github/workflows/reusable-upload.yml#L187)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Related to earlier comment. Is this resulting version string used in all the appropriate places?
</blockquote></details>

Did you have some particular place in mind?

We don't use the version string for much wrt pybatfish in this workflow. We mainly pass around the wheel (which has the version number embedded in it)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/106)* status: all files reviewed, 2 unresolved discussions (waiting on @sfraint)

___
*[`.github/workflows/reusable-upload.yml` line 31 at r2](https://reviewable.io/reviews/batfish/docker/106#-NAzborn6OXCsU-E6JBb:-NAztzTgCvN8B3HL1Sag:b-9qkjvy) ([raw file](https://github.com/batfish/docker/blob/2ce4abdc924b7d18f13f568b57f7785f0c03b809/.github/workflows/reusable-upload.yml#L31)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Not needed (at least yet) - we're checking the repos to make sure they're in the batfish org, then we need the pybf ref to create a release branch from.

We don't do anything with the Batfish ref yet.
</blockquote></details>

Couldn't you make the same argument that pybatfish ref is not needed yet? I'd either add both or neither.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/106)* status: all files reviewed, 2 unresolved discussions (waiting on @arifogel and @sfraint)

___
*[`.github/workflows/reusable-upload.yml` line 31 at r2](https://reviewable.io/reviews/batfish/docker/106#-NAzborn6OXCsU-E6JBb:-NB-8Npv3UZkv6_NPr-l:b-lonucz) ([raw file](https://github.com/batfish/docker/blob/2ce4abdc924b7d18f13f568b57f7785f0c03b809/.github/workflows/reusable-upload.yml#L31)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Couldn't you make the same argument that pybatfish ref is not needed yet? I'd either add both or neither.
</blockquote></details>

We need the pybf ref to create the release branch from

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/106)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[`.github/workflows/reusable-upload.yml` line 31 at r2](https://reviewable.io/reviews/batfish/docker/106#-NAzborn6OXCsU-E6JBb:-NB-RlWP1GED3bmAwkUq:b-x8kk6d) ([raw file](https://github.com/batfish/docker/blob/2ce4abdc924b7d18f13f568b57f7785f0c03b809/.github/workflows/reusable-upload.yml#L31)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

We need the pybf ref to create the release branch from
</blockquote></details>

The point is that only one is configurable, unless I misunderstand how batfish code is fetched.. You could have hardcoded master for pybatfish ref, and then neither would be configurable. Seems odd to only make one configurable. Not worth spending any more time on it right now, though.
Also if I'm wrong about being able to configure batfish branch, all moot.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/106)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

___
*[`.github/workflows/reusable-upload.yml` line 31 at r2](https://reviewable.io/reviews/batfish/docker/106#-NAzborn6OXCsU-E6JBb:-NBI_tiw5GnocZ9CzL57:b-pk874r) ([raw file](https://github.com/batfish/docker/blob/2ce4abdc924b7d18f13f568b57f7785f0c03b809/.github/workflows/reusable-upload.yml#L31)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

The point is that only one is configurable, unless I misunderstand how batfish code is fetched.. You could have hardcoded master for pybatfish ref, and then neither would be configurable. Seems odd to only make one configurable. Not worth spending any more time on it right now, though.
Also if I'm wrong about being able to configure batfish branch, all moot.
</blockquote></details>

Both ref and repo are configurable for Batfish and Pybatfish in the `precommit` pipeline, which is where we checkout the code and build artifacts. I'll add some more comments in the `upload` workflow to make it more clear what is going on.

We're only restricting the repo during `upload` and we don't need to checkout Batfish again during `upload`.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/106)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/docker/106#-NBJAruGAi_2M_e6Wwr4:-NBJAruGAi_2M_e6Wwr5:b-pvj8cn) (no related file):*
I ran the draft workflow and "released" artifacts as expected: https://github.com/batfish/docker/actions/runs/3002459254

1. [Batfish](https://hub.docker.com/layers/batfish/batfish/manual-test-2022.09.06.74/images/sha256-1d856c8aa051b795a3b68be06650bb46caf69eeb2449e3ce700cb75b04c80c5c?context=explore) and [Allinone](https://hub.docker.com/layers/batfish/allinone/manual-test-2022.09.06.74/images/sha256-4947647c427dc0e8abd03500a8023e01c43bbafd28e0e8bbe9c0dc5629435a52?context=explore) containers were released with modified tags
2. Pybatfish "release" branch was pushed: https://github.com/batfish/pybatfish/tree/github-actions-test-2022.09.06.74
3. I intentionally skipped the Pybatfish wheel upload since the wheel upload would be public / affect users

___

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/106)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @arifogel and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/docker/106#-NBJAruGAi_2M_e6Wwr4:-NBJCx3j4syGVFkxlopI:b-a0o2vf) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

I ran the draft workflow and "released" artifacts as expected: https://github.com/batfish/docker/actions/runs/3002459254

1. [Batfish](https://hub.docker.com/layers/batfish/batfish/manual-test-2022.09.06.74/images/sha256-1d856c8aa051b795a3b68be06650bb46caf69eeb2449e3ce700cb75b04c80c5c?context=explore) and [Allinone](https://hub.docker.com/layers/batfish/allinone/manual-test-2022.09.06.74/images/sha256-4947647c427dc0e8abd03500a8023e01c43bbafd28e0e8bbe9c0dc5629435a52?context=explore) containers were released with modified tags
2. Pybatfish "release" branch was pushed: https://github.com/batfish/pybatfish/tree/github-actions-test-2022.09.06.74
3. I intentionally skipped the Pybatfish wheel upload since the wheel upload would be public / affect users
</blockquote></details>

(this was at `r5`)

___

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/106)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

**Review by arifogel — COMMENTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/106)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/106)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

___
*[`.github/workflows/cross_version_test.yml` line 59 at r2](https://reviewable.io/reviews/batfish/docker/106#-NAzPnuu9X6qiR21Uqyw:-NBJFgTc4M4EvSGbZdFP:b-vqvver) ([raw file](https://github.com/batfish/docker/blob/2ce4abdc924b7d18f13f568b57f7785f0c03b809/.github/workflows/cross_version_test.yml#L59)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

I sprinkled some `TODO`s around, for the changes I will need to make before merging this workflow - to actually publish release artifacts.
</blockquote></details>

These should all be resolved now, the workflow should be fully functional once merged.

**Pull request merged**
