### PR TITLE
Update dev readme with instructions for release

### PR DESCRIPTION
**Pull request by sfraint**
Update dev readme with instructions for building, testing, and release

### CODE REVIEW

**Review by progwriter — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/20)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint and @anothermattbrown)

___
*[README.dev.md, line 18 at r1](https://reviewable.io/reviews/batfish/docker/20#-LT1Mx7C0OJA-j6x6iao:-LT1Mx7C0OJA-j6x6iap:b99ahtu) ([raw file](https://github.com/batfish/docker/blob/7f4496e5cebd97be2fd3eca554783fdc6b38f062/README.dev.md#L18)):*
> ```Markdown
>    BATFISH_TAG=ABCDEF
>    PYBATFISH_TAG=123456
>    ```
> ```

why not mod the script to export these automatically?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/20)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @progwriter and @anothermattbrown)

___
*[README.dev.md, line 18 at r1](https://reviewable.io/reviews/batfish/docker/20#-LT1Mx7C0OJA-j6x6iao:-LT3Uwfj4NAlMcktvuOr:bepdteq) ([raw file](https://github.com/batfish/docker/blob/7f4496e5cebd97be2fd3eca554783fdc6b38f062/README.dev.md#L18)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

why not mod the script to export these automatically? 
</blockquote></details>

Fixed instructions to use `source` instead of `sh` to invoke the script; now the env vars set in the script apply to the invoking env.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

___
*[README.dev.md, line 18 at r1](https://reviewable.io/reviews/batfish/docker/20#-LT1Mx7C0OJA-j6x6iao:-LTTXfI4CZH2r-x6y9oz:b-wbtlv0) ([raw file](https://github.com/batfish/docker/blob/7f4496e5cebd97be2fd3eca554783fdc6b38f062/README.dev.md#L18)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Fixed instructions to use `source` instead of `sh` to invoke the script; now the env vars set in the script apply to the invoking env.
</blockquote></details>

OK - undid this for now, will just require user to set these vars to avoid sourcing other things as well

**Review by progwriter — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/20#-:-LTTYDWw65LOFtfuBO3B:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anothermattbrown)

**Pull request merged**
