### PR TITLE
Docker: upgrade to java 11 in ci-base

### PR DESCRIPTION
**Pull request by dhalperi**

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/67)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @arifogel, @dhalperi, and @progwriter)

___
*[build-infra/Dockerfile, line 73 at r1](https://reviewable.io/reviews/batfish/docker/67#-MK1V9QjEYXNk7Usljby:-MK1V9QjEYXNk7Usljbz:bmiprow) ([raw file](https://github.com/batfish/docker/blob/11d1ef17d2314f884bc314ff189524fd2b0e617d/build-infra/Dockerfile#L73)):*
> ```Dockerfile
> ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64/
> # Set Java to obey cgroup limits
> ENV _JAVA_OPTIONS -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1
> ```

Need to change java options

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/67)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @arifogel and @progwriter)

___
*[build-infra/Dockerfile, line 73 at r1](https://reviewable.io/reviews/batfish/docker/67#-MK1V9QjEYXNk7Usljby:-MK1VDxz1DJBtmKnTVUx:b-psd5ni) ([raw file](https://github.com/batfish/docker/blob/11d1ef17d2314f884bc314ff189524fd2b0e617d/build-infra/Dockerfile#L73)):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

Need to change java options
</blockquote></details>

Yep, waiting for it to fail in CI.

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/67)* status: all files reviewed, 1 unresolved discussion (waiting on @arifogel and @progwriter)

**Review by arifogel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/67)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @progwriter)

**Comment by dhalperi** [comment]
Passing precommit with latest: https://buildkite.com/batfish/batfish-pre-commit/builds/26618#_

**Review by dhalperi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/67)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @progwriter)

**Pull request merged**
