### PR TITLE
update ci-base for 18.04

### PR DESCRIPTION
**Pull request by arifogel**
- use Ubuntu 18.04
- use OpenJDK 11
- use bazel 0.23.0

### CODE REVIEW

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/24)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/docker/24#-LZqee8YEyeRRWG7UHqI:-LZqee8YEyeRRWG7UHqJ:bohcg8a) (no related file):*
self-merge only.
Need to do manual testing.

---

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/24)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dhalperi)

*[a discussion](https://reviewable.io/reviews/batfish/docker/24#-LZqee8YEyeRRWG7UHqI:-LZqsO-Z3H0_s4p8WWAX:bjfda1e) (no related file):*
<details><summary><i>Previously, arifogel (Ari Fogel) wrote…</i></summary><blockquote>

self-merge only.
Need to do manual testing.
</blockquote></details>

Manual testing succeeded.

---

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/24)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[build-infra/Dockerfile, line 29 at r2](https://reviewable.io/reviews/batfish/docker/24#-LZqvDya6U4TEqd_XS7X:-LZqvDya6U4TEqd_XS7Y:bjwwrtv) ([raw file](https://github.com/batfish/docker/blob/4aac755832b9cfa7735cdc109d58831e9dee4124/build-infra/Dockerfile#L29)):*
> ```Dockerfile
>     python-minimal \
>     python3-dev \
>     rsync \
> ```

why? no longer installed / needed for some later script?
___
*[build-infra/Dockerfile, line 34 at r2](https://reviewable.io/reviews/batfish/docker/24#-LZqvDVj36L8d-AsK4Nq:-LZqvDVj36L8d-AsK4Nr:bithlox) ([raw file](https://github.com/batfish/docker/blob/20ea5b00366ab004184e12742ef222c086f65d22/build-infra/Dockerfile#L34)):*
> ```Dockerfile
>     zip \
> &&  rm -rf /var/lib/apt/lists/* \
>     /var/cache/oracle-jdk8-installer \
> ```

why? no longer leaving temp space around for java?
___
*[build-infra/Dockerfile, line 81 at r2](https://reviewable.io/reviews/batfish/docker/24#-LZqvAFU8OWfWLanV1OU:-LZqvAFU8OWfWLanV1OV:bxps4yl) ([raw file](https://github.com/batfish/docker/blob/4aac755832b9cfa7735cdc109d58831e9dee4124/build-infra/Dockerfile#L81)):*
> ```
> -DskipTests=false -Dmaven.javadoc.skip=false
> ```

just `-p !fast` at this point?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/24)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[build-infra/Dockerfile, line 81 at r2](https://reviewable.io/reviews/batfish/docker/24#-LZqvAFU8OWfWLanV1OU:-LZqvXuxBmpm_-c0-6K_:bjc4lje) ([raw file](https://github.com/batfish/docker/blob/4aac755832b9cfa7735cdc109d58831e9dee4124/build-infra/Dockerfile#L81)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

> ```
> -DskipTests=false -Dmaven.javadoc.skip=false
> ```

just `-p !fast` at this point?
</blockquote></details>

To be fair, the goal was to be fast and download stuff... not to ensure that a dry-run of the container will pass all tests. So I think this is probably okay as-is actually.

**Comment by dhalperi** [comment]
___
*[build-infra/Dockerfile, line 81 at r2](https://reviewable.io/reviews/batfish/docker/24#-LZqvAFU8OWfWLanV1OU:-LZqvdQM20DsObXl9Ywc:b-v4ry88) ([raw file](https://github.com/batfish/docker/blob/4aac755832b9cfa7735cdc109d58831e9dee4124/build-infra/Dockerfile#L81)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

To be fair, the goal was to be fast and download stuff... not to ensure that a dry-run of the container will pass all tests. So I think this is probably okay as-is actually.
</blockquote></details>

(as-was)

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/24)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[build-infra/Dockerfile, line 29 at r2](https://reviewable.io/reviews/batfish/docker/24#-LZqvDya6U4TEqd_XS7X:-LZqvefZCJuM3BpCMRVt:b-3x6bqi) ([raw file](https://github.com/batfish/docker/blob/4aac755832b9cfa7735cdc109d58831e9dee4124/build-infra/Dockerfile#L29)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why? no longer installed / needed for some later script?
</blockquote></details>

No longer installed by default.
See https://buildkite.com/batfish/batfish-pre-commit/builds/2852#03a73fda-4591-4a07-90a2-f45f9d22257c
"Maven tests + coverage"

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/24)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @arifogel and @dhalperi)

___
*[build-infra/Dockerfile, line 34 at r2](https://reviewable.io/reviews/batfish/docker/24#-LZqvDVj36L8d-AsK4Nq:-LZqvsYC2A46fMRrx-Fi:buzttqw) ([raw file](https://github.com/batfish/docker/blob/20ea5b00366ab004184e12742ef222c086f65d22/build-infra/Dockerfile#L34)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

why? no longer leaving temp space around for java?
</blockquote></details>

This wasn't necessary even before. This only applies to the proprietary JDK8 installer (not OpenJDK), which would have been used on Ubuntu 14.04.
I checked the docker image fs to confirm.

**Review by arifogel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/24)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @dhalperi)

___
*[build-infra/Dockerfile, line 81 at r2](https://reviewable.io/reviews/batfish/docker/24#-LZqvAFU8OWfWLanV1OU:-LZqw8Pc9GXgWCKf055g:b-j36ruj) ([raw file](https://github.com/batfish/docker/blob/4aac755832b9cfa7735cdc109d58831e9dee4124/build-infra/Dockerfile#L81)):*
<details><summary><i>Previously, dhalperi (Dan Halperin) wrote…</i></summary><blockquote>

(as-was)
</blockquote></details>

This causes more stuff to be downloaded, so an argument could be made to leave it.

**Review by dhalperi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/24#-:-LZr45aJ2Mw1dXXc3t2y:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @dhalperi)

**Pull request merged**
