### PR TITLE
Run Pybatfish tests inside allinone

### PR DESCRIPTION
**Pull request by sfraint**
Run Pybatfish tests inside `allinone` container to:
* Make testing more self-contained (no longer conflict with Batfish ports on host machine)
* Run tests in an environment more similar to actual deployed environment (rather than running on host machine, should help catch issues with Docker container packaging)

### CODE REVIEW

**Review by progwriter — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/27)* status: all files reviewed, 3 unresolved discussions (waiting on @dhalperi and @sfraint)

___
*[build_images.sh, line 26 at r2](https://reviewable.io/reviews/batfish/docker/27#-LaHO8iA9-2MrdwnyibD:-LaHO8iA9-2MrdwnyibE:b-4i91r3) ([raw file](https://github.com/batfish/docker/blob/cc664cbcd6ccbf653909027b6c189a72d861e123/build_images.sh#L26)):*
> ```Shell
> function cleanup_dirs {
>     # Testing writes pycache files as root
>     sudo rm -rf ${TEMP_DIR}
> ```

not a fan of this. Is there anything else we can do? disable python caching? force pytest to clean it up after test run is finished? switch users after doing `docker run`?
___
*[tests/test.sh, line 18 at r2](https://reviewable.io/reviews/batfish/docker/27#-LaHNZYW2nryNcLxWUaG:-LaHNZYW2nryNcLxWUaH:b-lt8p00) ([raw file](https://github.com/batfish/docker/blob/cc664cbcd6ccbf653909027b6c189a72d861e123/tests/test.sh#L18)):*
> ```Shell
> echo waiting for batfish to start
> # Poll until we can connect to the coordinator
> while ! curl http://localhost:9996/
> ```

should there be some timeout? or max tries?
___
*[tests/test.sh, line 30 at r2](https://reviewable.io/reviews/batfish/docker/27#-LaHNRRK92Ba9cJVmYBX:-LaHNRRLE9640-i8vHTp:b-olk3f7) ([raw file](https://github.com/batfish/docker/blob/cc664cbcd6ccbf653909027b6c189a72d861e123/tests/test.sh#L30)):*
> ```Shell
> echo starting integration tests
> pytest tests/integration
> echo done with tests
> ```

nit: do you not need quotes around echo strings?

**Review by dhalperi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/27)* status: all files reviewed, 4 unresolved discussions (waiting on @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/docker/27#-LaHPQoi3sxKVl91ZHDo:-LaHPQoj-2CUNsDkskQT:b-8m578v) (no related file):*
Blocked on design approval.

---

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/27)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @progwriter)

___
*[build_images.sh, line 26 at r2](https://reviewable.io/reviews/batfish/docker/27#-LaHO8iA9-2MrdwnyibD:-LaXD0nQ-9bD6roszQEY:b-uc67di) ([raw file](https://github.com/batfish/docker/blob/cc664cbcd6ccbf653909027b6c189a72d861e123/build_images.sh#L26)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

not a fan of this. Is there anything else we can do? disable python caching? force pytest to clean it up after test run is finished? switch users after doing `docker run`?
</blockquote></details>

Looks like we can use a combination of `py3clean` and skipping pytest caching to clean this up inside the container.
___
*[tests/test.sh, line 18 at r2](https://reviewable.io/reviews/batfish/docker/27#-LaHNZYW2nryNcLxWUaG:-LaSbKzVCEQvUvOAD8vf:b-896fix) ([raw file](https://github.com/batfish/docker/blob/cc664cbcd6ccbf653909027b6c189a72d861e123/tests/test.sh#L18)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

should there be some timeout? or max tries?
</blockquote></details>

Done.
___
*[tests/test.sh, line 30 at r2](https://reviewable.io/reviews/batfish/docker/27#-LaHNRRK92Ba9cJVmYBX:-LaSbAPa69DcYEQHIPpV:b-pll0rz) ([raw file](https://github.com/batfish/docker/blob/cc664cbcd6ccbf653909027b6c189a72d861e123/tests/test.sh#L30)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

nit: do you not need quotes around echo strings?
</blockquote></details>

Correct, quotes are not needed since all echo args are printed

**Review by progwriter — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/docker/27)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
